### ISSUE TITLE
There is no way to close program without killing it.

### ISSUE THREAD

**Issue by jaroslaw-janikowski** [tsoding/sowon#24]
Now, to exit sowon, one has to find its PID in process list and type "kill" command in terminal. It's very uncomfortable. It would be nice to have CTRL+Q shortcut for closing this program.

**Comment by jaroslaw-janikowski** [comment]
#25 My pull request
Sorry if i did something wring, its my first pull request on github :)

**Comment by rexim** [comment]
@jaroslaw-janikowski excuse me, may I ask you what OS and Window Manager are you using? We do [handle](https://github.com/tsoding/sowon/blob/85dbbd06e7f20fe0a727fcb34e5206c23894ff83/main.c#L201) [SDL_QUIT](https://wiki.libsdl.org/SDL_EventType#SDL_QUIT) event which makes this program closable via <kbd>Alt+F4</kbd> (or similar) in the majority of the OS-es and WM-s where SDL is supported.

**Comment by jaroslaw-janikowski** [comment]
@rexim I use Ubuntu 18.04.5 LTS with i3. Apparently SIGTERM is not connected to any keyboard shortcut. Thanks for guiding me on this. Feel free to close this issue.

**Comment by rexim** [comment]
@jaroslaw-janikowski sure! No problem!
